from __future__ import annotations

import hashlib
import io
import json
import re
import zipfile

from core.leica.authoritative import read_authoritative_member


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_") or "leica_look"


def generated_injector_source() -> bytes:
    source = read_authoritative_member("uploader.py").decode("utf-8")
    source = source.replace(
        "if len(out)!=MAX_DOWNLOADABLE_LOOKS:\n        raise SystemExit(f\"expected {MAX_DOWNLOADABLE_LOOKS} Looks, got {len(out)}\")",
        "if not out or len(out)>MAX_DOWNLOADABLE_LOOKS:\n        raise SystemExit(f\"expected 1..{MAX_DOWNLOADABLE_LOOKS} Looks, got {len(out)}\")",
    )
    source = source.replace(
        'print("AUTO-INSTALL: 9-Look final Infinite Arch set.")',
        'print(f"AUTO-INSTALL: generated {len(manifest)}-Look package.")',
    )
    source = source.replace('assets=validate(root,manifest)',
                            'assets=validate(root,manifest); manifest=[L for L,_,_ in assets]')
    source = source.replace("final IA Looks", "package Looks").replace("final nine", "complete package")
    return source.encode("utf-8")


def package_readme(name: str, look_id: int, base_name: str, provenance: str, payload_sha256: str) -> bytes:
    return f"""# {name}

Generated by Film Look Studio.

## Look

- ID: {look_id}
- Leica base: {base_name}
- Payload SHA-256: `{payload_sha256}`
- Source provenance: {provenance}

## Prepare on iPhone

Download and extract this entire ZIP in the iPhone Files app. Open
`injector.py` from the extracted folder in an iPhone Python interpreter.
The injector embeds its manifest, CUBE and icon with checksum validation.
It can run by itself; keep the rest of the package as an editable source record.

If the interpreter provides a terminal, you can validate without connecting:
`python injector.py --list`.

## Install from iPhone

The Replit web application never connects to a camera. `injector.py` is the
v1.2 proven FOTOS-assisted uploader adapted only to accept a generated package
containing 1–9 Looks, with assets embedded for standalone use. No computer is used in the installation workflow.

1. On the iPhone, open Leica FOTOS and connect to the camera normally.
2. Wait until FOTOS confirms that the camera is connected.
3. Without disconnecting or changing the camera network, use the iPhone app
   switcher to return to the Python interpreter.
4. Open `injector.py` and tap the interpreter's Run or Play button. If the
   interpreter uses a terminal, run `python injector.py`.
5. The script validates every asset, reads the current Look table, performs a
   single-attempt write, re-reads the table, and reports verification.

Do not rerun after an ambiguous network failure until the camera state has been
inspected. Existing downloadable Looks can consume the camera's nine slots.
""".encode()


def cheat_sheet(name: str, look_id: int, base_name: str, description: str, provenance: str) -> bytes:
    return f"""# {name}

**Look ID:** {look_id}  
**Leica Base:** {base_name}

## Style

{description or "Custom Leica Look generated from user-supplied color material."}

## Source

{provenance}

## Leica payload

- D861: {look_id}
- DC44: {name}
- DC86: VALID 180×90 1-bit BMP
- D860: VALID 17³ CUBE
- D864: 2
- D866: {base_name}
- Round trip: PASS

## Install

On the iPhone, connect to the camera in Leica FOTOS, switch back to the Python
interpreter without disconnecting, and tap Run or Play on `injector.py`. The web
application itself does not connect to the camera.
""".encode()


def build_look_package(
    *,
    name: str,
    look_id: int,
    base: int,
    icon: bytes,
    cube: bytes,
    payload: bytes,
    provenance: str,
    description: str,
    graph: dict | None = None,
    source_components: list[dict] | None = None,
) -> bytes:
    slug = slugify(name)
    base_name = "Monochrome" if base == 1 else "Standard"
    manifest_record = {
        "key": slug,
        "name": name,
        "id": look_id,
        "base": base,
        "base_name": base_name,
        "mono": base == 1,
        "enabled": True,
        "cube_sha256": hashlib.sha256(cube).hexdigest(),
        "icon_sha256": hashlib.sha256(icon).hexdigest(),
        "cube": f"looks/{slug}/look.CUBE",
        "cube_bytes": len(cube),
        "icon": f"looks/{slug}/look.bmp",
        "icon_bytes": len(icon),
        "payload_sha256": hashlib.sha256(payload).hexdigest(),
        "payload": f"looks/{slug}/look.leica-payload.bin",
        "compiler": "Film Look Studio compiler v1",
        "round_trip_verified": True,
        "source_provenance": provenance,
    }
    files = {
        "injector.py": self_contained_injector([manifest_record], {manifest_record["cube"]: cube, manifest_record["icon"]: icon}),
        "looks_manifest.json": json.dumps([manifest_record], indent=2, sort_keys=True).encode(),
        f"looks/{slug}/look.CUBE": cube,
        f"looks/{slug}/look.bmp": icon,
        f"looks/{slug}/look.leica-payload.bin": payload,
        "README.md": package_readme(name, look_id, base_name, provenance, manifest_record["payload_sha256"]),
        "CHEAT_SHEET.md": cheat_sheet(name, look_id, base_name, description, provenance),
        "sources/provenance.json": json.dumps({"description": description, "provenance": provenance, "components": source_components or []}, indent=2).encode(),
    }
    if graph is not None:
        files["look-graph.json"] = json.dumps(graph, indent=2, sort_keys=True).encode()
    checksums = "\n".join(f"{hashlib.sha256(data).hexdigest()}  {path}" for path, data in sorted(files.items())) + "\n"
    files["checksums.txt"] = checksums.encode()
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w") as archive:
        for path, data in sorted(files.items()):
            info = zipfile.ZipInfo(path, date_time=(2026, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, data)
    return output.getvalue()

def self_contained_injector(manifest: list[dict], assets: dict[str, bytes]) -> bytes:
    """Embed validated assets without changing the reference transport functions."""
    import base64
    source = generated_injector_source().decode()
    replacements = {
        'cube=(root/L["cube"]).read_bytes(); icon=(root/L["icon"]).read_bytes()':
        'cube=base64.b64decode(ASSETS[L["cube"]], validate=True); icon=base64.b64decode(ASSETS[L["icon"]], validate=True)',
        'manifest=json.loads((root/"looks_manifest.json").read_text())': 'manifest=EMBEDDED_MANIFEST',
    }
    for old, new in replacements.items():
        if source.count(old) != 1:
            raise RuntimeError("Authoritative injector template changed; review adapter before export")
        source = source.replace(old, new)
    # Literal Python data, never interpolation into executable expressions.
    embedded = '\nimport base64\nEMBEDDED_MANIFEST = ' + repr(manifest)
    embedded += '\nASSETS = ' + repr({path: base64.b64encode(data).decode('ascii') for path, data in assets.items()}) + '\n'
    anchor = 'HOST="192.168.54.1"'
    if source.count(anchor) != 1:
        raise RuntimeError("Authoritative injector anchor changed")
    return source.replace(anchor, embedded + '\n' + anchor).encode()


def combine_look_packages(packages: list[bytes]) -> bytes:
    """Produce one installable pack, not nested installers that reject each other."""
    if not 1 <= len(packages) <= 9:
        raise ValueError("Select between one and nine Looks")
    manifest, files, assets = [], {}, {}
    ids, names, paths = set(), set(), set()
    for index, package in enumerate(packages, 1):
        with zipfile.ZipFile(io.BytesIO(package)) as archive:
            records = json.loads(archive.read("looks_manifest.json"))
            if len(records) != 1:
                raise ValueError("Expected one Look per source package")
            record = records[0]
            if record['id'] in ids:
                raise ValueError(f"Duplicate Leica Look ID {record['id']}; assign distinct Look IDs before building a pack")
            if record['name'] in names:
                raise ValueError("Each Look in a pack must have a distinct name")
            ids.add(record['id']); names.add(record['name']); manifest.append(record)
            for key in ('cube', 'icon', 'payload'):
                path = record[key]
                if path in paths:
                    raise ValueError("Look names resolve to the same package path; rename one Look")
                paths.add(path); files[path] = archive.read(path)
                if key != 'payload':
                    assets[path] = files[path]
            for name in ('README.md', 'CHEAT_SHEET.md', 'sources/provenance.json', 'look-graph.json'):
                if name in archive.namelist():
                    files[f'documentation/{index:02d}/{name}'] = archive.read(name)
    files['looks_manifest.json'] = json.dumps(manifest, indent=2, sort_keys=True).encode()
    files['injector.py'] = self_contained_injector(manifest, assets)
    files['README.md'] = ("# Leica Look pack\n\nRun the single self-contained injector.py on your iPhone to install all selected Looks.\n"
                          "Connect in Leica FOTOS, switch to your Python interpreter while remaining connected, and tap Run.\n"
                          "Validate offline with `python injector.py --list`.\n\n"
                          "Each Look's editable graph, provenance and cheat sheet are under documentation/.\n"
                          "Existing non-matching downloadable Looks must be removed in FOTOS before installation.\n").encode()
    files['checksums.txt'] = ''.join(f'{hashlib.sha256(data).hexdigest()}  {path}\n' for path, data in sorted(files.items())).encode()
    output = io.BytesIO()
    with zipfile.ZipFile(output, 'w') as archive:
        for path, data in sorted(files.items()):
            info = zipfile.ZipInfo(path, date_time=(2026, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, data)
    return output.getvalue()
