from __future__ import annotations

import hashlib
import io
import json
import re
import zipfile

from core.leica.authoritative import read_authoritative_member


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_") or "leica_look"


def generated_injector_source() -> bytes:
    source = read_authoritative_member("uploader.py").decode("utf-8")
    source = source.replace(
        "if len(out)!=MAX_DOWNLOADABLE_LOOKS:\n        raise SystemExit(f\"expected {MAX_DOWNLOADABLE_LOOKS} Looks, got {len(out)}\")",
        "if not out or len(out)>MAX_DOWNLOADABLE_LOOKS:\n        raise SystemExit(f\"expected 1..{MAX_DOWNLOADABLE_LOOKS} Looks, got {len(out)}\")",
    )
    source = source.replace(
        'print("AUTO-INSTALL: 9-Look final Infinite Arch set.")',
        'print(f"AUTO-INSTALL: generated {len(manifest)}-Look Infinite Arch package.")',
    )
    return source.encode("utf-8")


def package_readme(name: str, look_id: int, base_name: str, provenance: str, payload_sha256: str) -> bytes:
    return f"""# {name}

Generated by Infinite Arch Photo Lab.

## Look

- ID: {look_id}
- Leica base: {base_name}
- Payload SHA-256: `{payload_sha256}`
- Source provenance: {provenance}

## Validate without a camera

Run:

```bash
python3 injector.py --list
```

## Local installation

The Replit web application never connects to a camera. `injector.py` is the
v1.2 proven FOTOS-assisted local uploader adapted only to accept a generated
package containing 1–9 Looks.

1. Put this entire extracted folder on the local computer or Python-capable device.
2. Turn on the Leica and establish the normal Leica FOTOS connection.
3. Follow the known working v1.2 handoff: remain on the camera network and release
   FOTOS sockets as documented by the historical tests.
4. Run `python3 injector.py`.
5. The script validates every asset, reads the current Look table, performs a
   single-attempt write, re-reads the table, and reports verification.

Do not rerun after an ambiguous network failure until the camera state has been
inspected. Existing downloadable Looks can consume the camera's nine slots.
""".encode()


def cheat_sheet(name: str, look_id: int, base_name: str, description: str, provenance: str) -> bytes:
    return f"""# {name}

**Look ID:** {look_id}  
**Leica Base:** {base_name}

## Style

{description or "Custom Leica Look generated from user-supplied color material."}

## Source

{provenance}

## Leica payload

- D861: {look_id}
- DC44: {name}
- DC86: VALID 180×90 1-bit BMP
- D860: VALID 17³ CUBE
- D864: 2
- D866: {base_name}
- Round trip: PASS

## Install

Run `python3 injector.py` locally after establishing the documented Leica FOTOS
authorized state. The web application itself does not connect to the camera.
""".encode()


def build_look_package(
    *,
    name: str,
    look_id: int,
    base: int,
    icon: bytes,
    cube: bytes,
    payload: bytes,
    provenance: str,
    description: str,
) -> bytes:
    slug = slugify(name)
    base_name = "Monochrome" if base == 1 else "Standard"
    manifest_record = {
        "key": slug,
        "name": name,
        "id": look_id,
        "base": base,
        "base_name": base_name,
        "mono": base == 1,
        "enabled": True,
        "cube_sha256": hashlib.sha256(cube).hexdigest(),
        "icon_sha256": hashlib.sha256(icon).hexdigest(),
        "cube": f"looks/{slug}/look.CUBE",
        "cube_bytes": len(cube),
        "icon": f"looks/{slug}/look.bmp",
        "icon_bytes": len(icon),
        "payload_sha256": hashlib.sha256(payload).hexdigest(),
        "payload": f"looks/{slug}/look.leica-payload.bin",
        "compiler": "Infinite Arch Photo Lab compiler v1",
        "round_trip_verified": True,
        "source_provenance": provenance,
    }
    files = {
        "injector.py": generated_injector_source(),
        "looks_manifest.json": json.dumps([manifest_record], indent=2, sort_keys=True).encode(),
        f"looks/{slug}/look.CUBE": cube,
        f"looks/{slug}/look.bmp": icon,
        f"looks/{slug}/look.leica-payload.bin": payload,
        "README.md": package_readme(name, look_id, base_name, provenance, manifest_record["payload_sha256"]),
        "CHEAT_SHEET.md": cheat_sheet(name, look_id, base_name, description, provenance),
        "sources/provenance.json": json.dumps({"description": description, "provenance": provenance}, indent=2).encode(),
    }
    checksums = "\n".join(f"{hashlib.sha256(data).hexdigest()}  {path}" for path, data in sorted(files.items())) + "\n"
    files["checksums.txt"] = checksums.encode()
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w") as archive:
        for path, data in sorted(files.items()):
            info = zipfile.ZipInfo(path, date_time=(2026, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, data)
    return output.getvalue()